name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4
      - name: SETUP ERLANG/ELIXIR
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.15
      - name: CONFIGURE
        run: |
          echo "build --color=yes" >> .bazelrc
      - name: BUILD
        run: |
          bazelisk build //... \
            --verbose_failures
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4
      - name: SETUP ERLANG/ELIXIR
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.15
      - name: CONFIGURE
        working-directory: test
        run: |
          echo "build --color=yes" >> .bazelrc
      - name: BUILD & TEST
        working-directory: test
        run: |
          bazelisk test //...
      - name: CHECK LOGS
        working-directory: test
        run: |
          grep "2 tests, 0 failures" bazel-testlogs/two_file_test/test.log
      - name: EXPECTED FAILURES FAIL
        working-directory: test
        run: |
          ! bazelisk test //:failing_test
          ! bazelisk test //:broken_test
          ! bazelisk test //:empty_test
      - name: UPLOAD TEST LOGS
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bazel-testlogs
          path: |
            test/bazel-testlogs/*
  examples-basic:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4
      - name: SETUP ERLANG/ELIXIR
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.15
      - name: CONFIGURE
        working-directory: examples/basic
        run: |
          echo "build --color=yes" >> .bazelrc
      - name: BUILD & TEST
        working-directory: examples/basic
        run: |
          bazelisk test //...
  examples-internal-elixir:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v4
      - name: INSTALL OTP BUILD DEPS
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            libssl-dev
      - name: CONFIGURE
        working-directory: examples/internal-elixir
        run: |
          echo "build --color=yes" >> .bazelrc
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: BUILD & TEST
        working-directory: examples/internal-elixir
        run: |
          bazelisk test //... \
            --config=ie-26_2 \
            --toolchain_resolution_debug='@@rules_erlang~//tools:toolchain_type' \
            --toolchain_resolution_debug='@@rules_elixir~//:toolchain_type' \
            --verbose_failures \
            --action_env=PATH
